name: MacOS Tests

on:
  # Delete the following line before merging:
  pull_request:
  schedule:
    # Run every day at 11 PM.
    - cron:  '0 23 * * *'

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["ethereum_truffle", "ethereum_bench", "ethereum", "ethereum_vm", "wasm", "wasm_sym", "other"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install NPM
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install dependencies
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        EXTRAS="dev-noks"
        pip install -e .[$EXTRAS]
    - name: Install Dependencies
      run: |
        brew install bash
        brew tap ethereum/ethereum
        brew install solidity@4
        brew install wabt
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        make_vmtests(){
            DIR=`pwd`
            if  [ ! -f ethereum_vm/.done ]; then
                echo "Automaking VMTests" `pwd`
                cd ./tests/ && mkdir -p  ethereum_vm/VMTests_concrete && mkdir -p ethereum_vm/VMTests_symbolic
                rm -Rf vmtests; git clone https://github.com/ethereum/tests --depth=1 vmtests
                for i in ./vmtests/VMTests/*; do python ./auto_generators/make_VMTests.py $i; done
                for i in ./vmtests/VMTests/*; do python ./auto_generators/make_VMTests.py $i --symbolic; done
                rm -rf ./vmtests
                touch ethereum_vm/.done
            fi
            cd $DIR
        }

        make_wasm_tests(){
            DIR=`pwd`
            if  [ ! -f .wasm_done ]; then
                echo "Automaking WASM Tests" `pwd`
                cd ./tests/wasm
                ./generate_tests.sh
                touch .wasm_done
            fi
            cd $DIR
        }

        make_wasm_sym_tests(){
            DIR=`pwd`
            if  [ ! -f .wasm_sym_done ]; then
                echo "Automaking Symbolic WASM Tests" `pwd`
                cd ./tests/wasm_sym
                ./generate_symbolic_tests.sh
                touch .wasm_sym_done
            fi
            cd $DIR
        }

        install_truffle(){
            npm install -g truffle
        }

        run_truffle_tests(){
            COVERAGE_RCFILE=$GITHUB_WORKSPACE/.coveragerc
            mkdir truffle_tests
            cd truffle_tests
            truffle unbox metacoin
            coverage run -m manticore . --contract MetaCoin --workspace output
            # Truffle smoke test. We test if manticore is able to generate states
            # from a truffle project.
            count=$(find output/ -name '*tx' -type f | wc -l)
            if [ "$count" -ne 34 ]; then
                echo "Truffle test failed" `ls output/*tx -l | wc -l` "!= 34"
                return 1
            fi
            echo "Truffle test succeded"
            coverage xml
            cd ..
            cp truffle_tests/coverage.xml .
            return 0
        }

        run_tests_from_dir() {
            DIR=$1
            COVERAGE_RCFILE=$GITHUB_WORKSPACE/.coveragerc
            echo "Running only the tests from 'tests/$DIR' directory"
            pytest --durations=100 --cov=manticore --cov-config=$GITHUB_WORKSPACE/.coveragerc -n auto "tests/$DIR"
            coverage xml
        }

        # Test type
        case $TEST_TYPE in
            ethereum_vm)
                make_vmtests
                run_tests_from_dir $TEST_TYPE
                ;;
            ethereum_truffle)
                echo "Running truffle test"
                install_truffle
                run_truffle_tests
                ;;
            wasm)
                make_wasm_tests
                run_tests_from_dir $TEST_TYPE
                ;;
            wasm_sym)
                make_wasm_sym_tests ;&  # Fallthrough
            ethereum)               ;&  # Fallthrough
            ethereum_bench)         ;&  # Fallthrough
            other)
                run_tests_from_dir $TEST_TYPE
                ;;
            *)
                echo "Unknown TEST_TYPE: '$TEST_TYPE'"
                exit 3;
                ;;
        esac